### ISSUE TITLE
Constant stained glass not found

### ISSUE THREAD

**Issue by alair069** [thebigsmileXD/StainedGlass#1]
CRITICAL> Error: "Undefined class constant 'STAINED_GLASS'" (EXCEPTION) in "/plugins/StainedGlass-master/src/xenialdan/StainedGlass/Main" at line 17

**Comment by inxomnyaa** [comment]
the version of pocketmine that you use doesn't support the id. which do you use?

**Comment by inxomnyaa** [comment]
and ffs is it too hard to add a proper title

**Comment by alair069** [comment]
I use Tesseract

**Comment by inxomnyaa** [comment]
Ah i see. Yea, that dev team is too stupid to update their shit.
